use DBALMOXARIFADO
SELECT * FROM PRODUTO

ALTER TABLE ITENENTRADA
ADD QUANTIDADE INT ,
PRECO FLOAT,
TOTAL FLOAT

ALTER TABLE SAIDA
ADD FOREIGN KEY (IDITENSAIDA) REFERENCES ITENSAIDA (IDITENSAIDA)

ALTER TABLE SECRETARIA
ADD ENDEREÇO VARCHAR(100),
BAIRRO VARCHAR(100),
CIDADE VARCHAR(100),
ESTADO VARCHAR(100),
TELEFONE VARCHAR(100),
CNPJ VARCHAR (100)